name: 'Auto Docs Action'
description: 'Automatically update Python docstrings using Claude Code CLI'
author: 'Dominique Garmier'

branding:
  icon: 'book-open'
  color: 'blue'

inputs:
  anthropic_api_key:
    description: 'Your Anthropic API key for Claude Code'
    required: true
  max_retries:
    description: 'Maximum number of retry attempts per file'
    required: false
    default: '2'
  claude_command:
    description: 'Path to Claude Code CLI executable'
    required: false
    default: 'claude'

outputs:
  files_processed:
    description: 'Total number of Python files processed'
  files_successful:
    description: 'Number of files successfully updated'
  files_failed:
    description: 'Number of files that failed processing'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install UV
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Claude Code CLI
      shell: bash
      run: |
        npm install -g @anthropic-ai/claude-code

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        uv sync

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Run auto-docs action
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        CLAUDE_COMMAND: ${{ inputs.claude_command }}
        MAX_RETRIES: ${{ inputs.max_retries }}
      run: |
        cd ${{ github.action_path }}
        python_output=$(uv run python main.py 2>&1)
        exit_code=$?

        # Extract statistics from output
        files_processed=$(echo "$python_output" | grep -o "total_files': [0-9]*" | grep -o "[0-9]*" || echo "0")
        files_successful=$(echo "$python_output" | grep -o "successful': [0-9]*" | grep -o "[0-9]*" || echo "0")
        files_failed=$(echo "$python_output" | grep -o "failed': [0-9]*" | grep -o "[0-9]*" || echo "0")

        # Set outputs
        echo "files_processed=$files_processed" >> $GITHUB_OUTPUT
        echo "files_successful=$files_successful" >> $GITHUB_OUTPUT
        echo "files_failed=$files_failed" >> $GITHUB_OUTPUT

        # Print output for debugging
        echo "$python_output"

        exit $exit_code
