"""Constants and configuration values used throughout the application."""

from __future__ import annotations


class Timeouts:
    """Timeout values for various operations."""
    
    CLAUDE_CLI_TIMEOUT = 120  # 2 minutes for Claude CLI operations
    GIT_COMMAND_TIMEOUT = 30  # 30 seconds for git commands
    SUBPROCESS_DEFAULT_TIMEOUT = 30  # Default subprocess timeout


class GitBot:
    """GitHub Actions bot configuration."""
    
    NAME = "github-actions[bot]"
    EMAIL = "41898282+github-actions[bot]@users.noreply.github.com"
    COMMIT_SUFFIX = "\n\n[skip ci] Auto-generated by auto-docs-action"


class ExitCodes:
    """Application exit codes."""
    
    SUCCESS = 0
    FAILURE = 1


class LogLimits:
    """Logging output limits."""
    
    STDOUT_PREVIEW_LENGTH = 1000  # Characters to show in stdout preview
    GIT_DIFF_PREVIEW_LENGTH = 200  # Characters to show in diff preview


class FilePatterns:
    """File patterns for git operations."""
    
    PYTHON_FILE_EXTENSION = ".py"
    PYTHON_FILES_PATTERN = "*.py"


# Emoji constants for consistent logging
class LogEmojis:
    """Emojis used in logging messages."""
    
    SUCCESS = "✅"
    ERROR = "❌"
    WARNING = "⚠️"
    INFO = "ℹ️"
    PROCESSING = "🔄"
    SEARCH = "🔍"
    ROBOT = "🤖"
    DOCUMENT = "📝"
    STATISTICS = "📊"
    PACKAGE = "📦"
    GEAR = "🔧"
    CLOCK = "⏰"
    CLIPBOARD = "📋"