"""Constants for the auto-docs GitHub Action."""

from __future__ import annotations

# Git-related constants
GITHUB_ACTIONS_BOT_NAME = "github-actions[bot]"
GITHUB_ACTIONS_BOT_EMAIL = "41898282+github-actions[bot]@users.noreply.github.com"
GITHUB_ACTIONS_BOT_PATTERNS = ["github-actions[bot]", "github-actions\\[bot\\]", "*github-actions*"]

# GitHub environment variables
ENV_GITHUB_EVENT_NAME = "GITHUB_EVENT_NAME"
ENV_GITHUB_BASE_REF = "GITHUB_BASE_REF"
ENV_GITHUB_HEAD_REF = "GITHUB_HEAD_REF"
ENV_GITHUB_REF_NAME = "GITHUB_REF_NAME"
ENV_GITHUB_SHA = "GITHUB_SHA"
ENV_GITHUB_OUTPUT = "GITHUB_OUTPUT"

# Application environment variables
ENV_CLAUDE_COMMAND = "CLAUDE_COMMAND"
ENV_MAX_RETRIES = "MAX_RETRIES"
ENV_RETRY_DELAY = "RETRY_DELAY"
ENV_ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY"
ENV_PRE_COMMIT_HOOK = "PRE_COMMIT_HOOK"

# Default values
DEFAULT_CLAUDE_COMMAND = "claude"
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY = 1.0

# Timeouts and limits
COMMAND_TIMEOUT_SECONDS = 30
CLAUDE_CLI_TIMEOUT_SECONDS = 120
LARGE_COMMIT_COUNT_FALLBACK = 999999

# File extensions and patterns
PYTHON_FILE_EXTENSION = ".py"
PYTHON_FILES_PATTERN = "*.py"
GIT_DIRECTORY = ".git"

# Git events
EVENT_PULL_REQUEST = "pull_request"
EVENT_PUSH = "push"

# Commit message components
SKIP_CI_TAG = "[skip ci]"
AUTO_DOCS_COMMIT_PREFIX = "docs: auto-update docstrings"
COMMIT_FOOTER_TEMPLATE = "\n\nCo-authored-by: {bot_name} <{bot_email}>"
AUTO_GENERATED_SUFFIX = "Auto-generated by auto-docs-action"

# CLI command components
CLAUDE_CLI_ARGS = ["--verbose", "--output-format", "json", "--allowedTools", "Edit", "Read"]

# Logging format
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
